unbind '%'
unbind '"'

bind '\' split-window -h
bind '-' split-window -v
bind 'x' kill-pane
bind 'X' kill-window
bind 'C-X' kill-session

bind -n 'M-Left' select-pane -L
bind -n 'M-Right' select-pane -R
bind -n 'M-Up' select-pane -U
bind -n 'M-Down' select-pane -D

bind -n 'C-M-Right' next-window
bind -n 'C-M-Left' previous-window

set -g mouse on

set-option -g allow-rename off

set -g status-left-length 256
set -g status-left ' #(hostname -I)'

set -g status-right-length 256
set -g status-right '%H:%M %d-%m-%Y ' 

set -g status-style fg=black,bg=color240

set -g window-status-format         ' #I:#W '
set -g window-status-current-format '[#I:#W]'

set -g status-justify absolute-centre

set -g mode-keys vi
bind -T copy-mode-vi 'v' send      -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel
bind 'P' paste-buffer

set  -g base-index       1
setw -g pane-base-index  1
set  -g renumber-windows on

set -g pane-border-style fg=color240
set -g pane-active-border-style fg=color240

