export C='/mnt/c'

# git
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_STATESEPARATOR="\[\033[38;5;240m\]"
export GIT_PS1_COMPRESSSPARSESTATE=1
export GIT_PS1_SHOWCONFLICTSTATE=1

# zoxide
export _ZO_RESOLVE_SYMLINKS=true
export _ZO_DOCTOR=0

